//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp4ISP9_14.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AppointmentFuture
    {
        public int ID { get; set; }
        public System.DateTime DateService { get; set; }
        public string TitleService { get; set; }
        public string Employee { get; set; }
    }
}
