//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp4ISP9_14.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InfoService3
    {
        public string Full_name_pation { get; set; }
        public string TitleService { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
